name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - run: pnpm install 
      # - run: pnpm run lint && pnpm run build
      - run: pnpm run build
