name: prettier-check
on:
    pull_request:
        branches: [master]
jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18
            - run: npx prettier --check src/*.*